### ISSUE TITLE
Update diff-includes to return 78 exit code for neutral response

### ISSUE THREAD

**Issue by lannonbr** [netlify/actions#6]
Instead of creating a file that would need to be consumed in the next action in the case that a file didn't differ. I think it could be easier to return the `78` exit code which stands for a neutral return in as described in the [Official Docs](https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#exit-codes-and-statuses). With this, then all following actions would be cancelled.

**Comment by kitop** [comment]
Thanks for the comment! 
I'll update the action to use `78` exit code, it wasn't available when we first created this :)

**Comment by kitop** [comment]
Oh, unfortunately, exit code `78` doesn't do exactly what we want to. From the docs:
> When an action returns this exit status, GitHub terminates all concurrently running actions and prevents any future actions from starting.

We don't want this action to stop concurrently running actions, only future ones that depend on it. Having that behavior lets us work more easily with monorepos with one workflow rather than having to define several ones for each app.

I'll give it some thought, but we might end up using the neutral exit code if we version the repo via tags to avoid breaking existing flows.

**Comment by lannonbr** [comment]
If that is the case, would it be fine if I created an action that implemented this where it would check for a specific diff and continue the workflow only if something changed. Then both styles can exist and people can choose which type they want?

**Comment by kitop** [comment]
Hi @lannonbr, you can use the branch `exit-code-78` which has the changes proposed. Just set your workflow action to `uses = "netlify/actions/build@exit-code-78"`. We'll keep it updated with any change to master.

**Comment by lannonbr** [comment]
Awesome!

**Comment by lannonbr** [comment]
I think I'm good with it being a separate branch so I am going to close this issue as it's been resolved
