### ISSUE TITLE
[build] 404 if git repo contains a period

### ISSUE THREAD

**Issue by curiouslychase** [netlify/actions#8]
Thanks for these awesome actions! 

I noticed while implementing the `build` action that I would get 404s for anytime a build was submitted when my `GITHUB_REPOSITORY` was `chaseadamsio/chaseonsoftware.com` (you can see this in [this run](https://github.com/chaseadamsio/chaseonsoftware/runs/75845593).

I had a theory that maybe this was due to having a . in the repository name, so I renamed my repo to be `chaseadamsio/chaseonsoftware`, pushed a new commit with the same config as the previous workflow and the [action completes succesfully](https://github.com/chaseadamsio/chaseonsoftware/runs/77214384). 

Is it possible that there's an issue in the way the repository name is handled?

**Comment by kitop** [comment]
Hi @chaseadamsio, thanks for reporting the issue!
While looking into it, I noticed [the first build](https://github.com/chaseadamsio/chaseonsoftware/runs/75845593) uses Netlify CLI, while the [second one](https://github.com/chaseadamsio/chaseonsoftware/runs/77214384) uses the `build` action with a Site ID. 
The first error seems related to not having run a build before trying the deploy command, and can't find the renaming event in [the comparison](https://github.com/chaseadamsio/chaseonsoftware/compare/bc9bf3083a43f98a1165706a098dadd8e403e6e5...19461df1621bc96c55f120a7be13a0a9eb4ddd2a). In there it seems that it worked (although the build timed out) when you changed the `SITE_ID` env variable to be the API's site id rather than name.

I'll try to reproduce the error with a repo with the dot in its name, but wanted to confirm the behavior in the meantime, if possible.

**Comment by chaseadamsio** [comment]
I changed it back to chaseonsoftware.com and got `Not Found`: https://github.com/chaseadamsio/chaseonsoftware.com/pull/68/checks?check_run_id=80378333

**Comment by curiouslychase** [comment]
Hey @kitop, here's what I've gotten:
- I changed the repo name back to `chaseonsoftware.com` and I've tried it with diff. flavors of `NETLIFY_SITE_ID` and in all cases I'm getting 404 Not Found: 
https://github.com/chaseadamsio/chaseonsoftware/runs/80382142
https://github.com/chaseadamsio/chaseonsoftware/runs/80384992

- I changed it back to `chaseonsoftware` and it succeeded:
https://github.com/chaseadamsio/chaseonsoftware/runs/80387894

**Comment by kitop** [comment]
@chaseadamsio I'm deploying a fix for this in a minute! (closed prematurely, sorry!)

**Comment by curiouslychase** [comment]
awesome! Thanks @kitop
